name: My First Pipeline

run-name: ${{ github.actor }} generated this run

on: [push, workflow_dispatch]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: show hello world
        run: echo "Hello World"
      - name: multi-line script
        run: |
          python --version
          pip --version
      # run a python cmd
      - name: Python Command
        run: |
          from datetime import datetime
          current_time = datetime.now().time()
          print("Current Time:", current_time)
        shell: python
              
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: list files
        run: |
          pwd
          ls
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.9' 
      - name: Show Python Version
        run: python --version
            


