name: My First Pipeline

run-name: ${{ github.actor }} generated this run

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: show hello world
        run: echo "Hello World"
      - name: multi-line script
        run: |
          python --version
          pip --version
      # run a python cmd
      - name: Python Command
        run: |
          from datetime import datetime
          current_time = datetime.now().time()
          print("Current Time:", current_time)
        shell: python
